version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dist

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 150
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 150
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 300
      runas: root  
