version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dist

permissions:
  - object: /
    pattern: "**"
    owner: jenkins
    group: jenkins

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 150
      runas: root
